logging.level:
  com.nurkiewicz: TRACE

elasticsearch:
  hosts:
    - http://192.168.2.120:9200
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000
#spring.metrics.export.graphite:
#  host: 192.168.99.100
#  port: 2003
#  protocol: Plaintext
#  step: PT1S
server:
  port: 8989
